### ISSUE TITLE
Prioritising newcomers to tech

### ISSUE THREAD

**Issue by ambrwlsn** [codebar/chapter-organiser-meetings#10]
codebar Berlin is getting more well-known and we have had waiting lists of 5-10 students each workshop for the last 3 or 4 workshops

We have a fairly large group of post-bootcampers who regularly attend codebar (as well as some regular attendees who we are not sure meet eligibility criteria). This means we tend to have people who list themselves as having 'no experience' or wanting to go through a beginner tutorial on the waiting list, and instead we help many people extend their bootcamp projects or with work they are being paid to do.

It’d be best if priority was given to those who are super new and looking to get into tech so that we can provide these people support and a friendly atmosphere also help them feel confident to continue trying. However it's not clear how we’d prioritise these people.

**Comment by ambrwlsn** [comment]
QA from Slack:
QU: Please can you share any of your methods for ensuring that only underrepresented students are taught at codebar? At the Berlin chapter we now often have students on the waiting list so it's definitely a pressing matter. What we are currently doing is preparing an intro talk that has a stronger emphasis on why codebar exists that'll be given at the next workshop, as well as a list of alternative meetups/workshops that non-underrepresented students can attend.

A: you can send eligibility check emails from the app and remove the students in question if they do not qualify

A: If someone comes along that you don’t think fits the eligibility criteria just gently ask them if they’ve read the eligibility criteria, if they say they have then leave it at that. If they haven’t then point them towards it. Sometimes people come along accidentally and sometimes people that don’t look like they fit the criteria are actually eligible.

**Comment by KimberleyCook** [comment]
- there is an eligibility email so send this if you're unsure if someone is eligible as a codebar coach
- send an email reminding students that they shouldn't be bringing paid/bootcamp work
