### ISSUE TITLE
Students from the host company

### ISSUE THREAD

**Issue by alextercete** [codebar/chapter-organiser-meetings#11]
The **Sponsorship Packages** section of [**Sponsoring**](http://manual.codebar.io/becoming-a-sponsor) mentions "_n_ spots at a codebar workshop or event for your employees" as a benefit of sponsoring.

Is it okay for employees from the _host company_ to attend if they meet the eligibility criteria?

**Comment by matyikriszta** [comment]
@alextercete yes, I think this should be allowed and happened in the London chapter before. As long as they fit the eligibility criteria they should be allowed to attend.

**Comment by alextercete** [comment]
Thanks, @matyikriszta! We actually managed to squeeze this one into yesterday's chapter organiser meeting, so I'll go ahead and close it.
