### ISSUE TITLE
Social Media Guidelines

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/chapter-organiser-meetings#12]
We're adding a new section in the manual for social media guidelines, I'd love to get input from a bunch of people with this.

**Comment by KimberleyCook** [comment]
Please always make sure codebar is spelt with a lowercase c

**Comment by KimberleyCook** [comment]
Please always send a thank you tweet after the workshop happens, making sure to tag the hosted company (if they have a tech twitter account add that too)

**Comment by KimberleyCook** [comment]
When announcing the workshop always add a link to the workshop

**Comment by KimberleyCook** [comment]
If you create a social media account (instagram/facebook ETC) please give the log in details to either myself, @matyikriszta or @despo, they need to be put into the codebar 1password account.

We now have team 1password accounts so one representative from each chapter can have full access to all these passwords.

**Comment by brunogirin** [comment]
Make sure any message follows the code of conduct. Does the CoC need to be extended to include communication outside the workshop?

**Comment by matyikriszta** [comment]
> If you create a social media account (instagram/facebook ETC) please give the log in details to either myself, @matyikriszta or @despo, they need to be put into the codebar 1password account.
> 
> We now have team 1password accounts so one representative from each chapter can have full access to all these passwords.

I would add here that the chapter representative with access to 1Pw should create these accounts and put the login details into 1Pw right away.

**Comment by KimberleyCook** [comment]
There is now a social media guidelines document. I will share with everyone after the meeting tomorrow https://docs.google.com/document/d/12Taf9WpvyHjmw0qEnQGvQSE5Vxk8M3xJeccEDZ0pGSw/edit?usp=sharing
