### ISSUE TITLE
Fund for students who want to go to a bootcamp like Makers

### ISSUE THREAD

**Issue by brunogirin** [codebar/chapter-organiser-meetings#14]
I got this question tonight from our newest host so here it is for comment:

> Has codebar ever considered creating a fund to help students who want to attend coding bootcamps like Makers?

**Comment by KimberleyCook** [comment]
codebar is going through the process of setting up a charity, as part of this we're putting together a 3 year development plan. 

Depending on how much funding codebar is able to receive once we're a charity this is a potential route to head down.
