### ISSUE TITLE
Better i18n support for chapters

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/chapter-organiser-meetings#16]
codebar currently supports internationalisation using a piece of software called Crowdin. However we could be making better use of this by adding more language support.

**Comment by matyikriszta** [comment]
@KimberleyCook we decided to remove the Crowdin integration as it was not working very well but people can still contribute by adding and editing the locale files in `config/locales`. I committed to writing a step by step tutorial for the codebar blog to encourage people contributing to the translations.

**Comment by matyikriszta** [comment]
* Kriszta to look into whether we can split languages files into smaller files
* Kriszta to write a step by step tutorial on how to contribute to translations

**Comment by KimberleyCook** [comment]
We are going to hire a freelancer to do the translations for the website.

Kim will start looking for a freelancer at the beginning of April.
