### ISSUE TITLE
Host feedback on eligibility criteria wording

### ISSUE THREAD

**Issue by brunogirin** [codebar/chapter-organiser-meetings#20]
I recently got feedback from a host on some wording in our eligibility criteria and in particular this phrase:

> We will try our best to **verify via social media profiles beforehand**, but if we cannot, we will contact you asking for a short confirmation that you have read this document and assert that you meet one or more of the criteria. We will never ask participants to specify which group.

The feedback is:

> There is a section on the website that says Codebar will check eligibility criteria by looking on Social Media profiles– we have had a couple of individuals raise this as a point of concern as they feel would be very hard to determine someones sexual orientation by looking on someone’s social media profile – is this something Codebar still actively do?

I agree with their feedback and we don't do it in West London. At most, we will ask for confirmation when we have a doubt but we take students' answers at face value, we don't attempt to verify in any way.

Is the verification through social media profile something other chapters do? If not, should it be removed from the eligibility criteria document?

**Comment by jmbriano** [comment]
We don't do it in Barcelona and i actually think it's not correct to do it. 
I remember we had this same concern some time ago. But we thought it was removed. Was it and now is back?

**Comment by matyikriszta** [comment]
@brunogirin @jmbriano we've been meaning to remove this for a while now, if anyone could open a PR to do so that would be great. I don't think any chapters do this really.

**Comment by KimberleyCook** [comment]
@matyikriszta @brunogirin I think this is something we can work on as we know we want to remove it, so no need to discuss at our next meeting.

**Comment by matyikriszta** [comment]
@KimberleyCook I agree, I was just hoping I won't have to do it myself 😂 I'll open a PR for this today.

**Comment by matyikriszta** [comment]
@KimberleyCook @brunogirin @jmbriano here's a pull request: https://github.com/codebar/planner/pull/1006. Feel free to suggest improvements to the copy.

**Comment by KimberleyCook** [comment]
@matyikriszta Thanks for doing this 💜
