### ISSUE TITLE
Social Media Fun

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/chapter-organiser-meetings#21]
I'm finding a lot of our Twitter accounts are announcing workshops and then thanking them, not much activity otherwise.

I want to know if anyone does anything fun with their twitter account to engage with our community a little more? 

**Some examples I know chapters have done previously:**
- During the workshop, go around groups and tweet saying what they're working on "Here we have @blah and @blah working on Intro to JavaScript with coach @blah". People will like/share if they're tagged to great promo for the chapter and also shows people not attending the variety of topics you can learn, again hopefully attracting more people.  
- #laptopstickersofcodebar - a photo of someone with their laptop showing off their great sticker collection.

**Comment by AliciateagleSR2** [comment]
Could Bristol have some Codebar Stickers @KimberleyCook :)

**Comment by AliciateagleSR2** [comment]
please :)

**Comment by daverick** [comment]
@raquelalvear: I am sure your will be interested in this!
