### ISSUE TITLE
Getting more organisers involved

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/chapter-organiser-meetings#23]
How do chapters go about getting more organisers involved?

**Comment by KimberleyCook** [comment]
- Dave (Barcelona) - Onboarding documents for new organisers, which makes it easy for someone to come onboard and delegate tasks to them
- Proper onboard materials when organisers come on board

ACTION
- Better onboarding materials for new organisers

**Comment by daverick** [comment]
i will just reference our Barcelona chapter on boarding guide:
https://github.com/codebar/barcelona/tree/master/processes/onboarding-new-organizers
might be useful for others chapter and maybe start to generalise it to all chapters.
