### ISSUE TITLE
Dealing with recruiters

### ISSUE THREAD

**Issue by brunogirin** [codebar/chapter-organiser-meetings#27]
I just hired a mid-level node.js developer and out of 40 CVs I received, not a single one was a woman. Therefore, I've been asking all of the agencies that contacted me if they had a diversity policy. As a result of that, I'm wondering whether there is something that codebar can do with recruiters to help them bring more diversity to the job market.

**Comment by KimberleyCook** [comment]
Whenever someone approaches someone from codebar about a junior developer job, please do direct them to the job board. This is there to help students get their first job. All jobs are vetted by us therefore, you will never see a job with a bunch of requirements, X number of years experience. This is also the only time codebar asks for money, so the £35 fee ask really does help us.

One task that came from this is to update some of the text on the website so explain what we allow in the postings and what we don't want to see. I've added a task for me to update the website.

**Comment by KimberleyCook** [comment]
The codebar website has been updated to reflect this feedback.
