### ISSUE TITLE
Chapter organiser request form

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/chapter-organiser-meetings#30]
Myself and @matyikriszta get quite a lot of requests on Slack from organisers. This is great, and 100% what as want as it's why we're here. However, sometimes these messages get lost, sometimes you have to ask us again and that isn't ideal. I know for myself I know someone has asked, but I can't remember who it was.

I was thinking, would it be useful for me to build a simple form that generates a ticket in Trello for me and Kriszta when you want something done (i.e add/remove an organiser, change your email, order stickers ETC).

I build something very similar at work a few years back and it was very useful. If this is something that you think would be help and be useful please let me know?

**Comment by garrettc** [comment]
I think this is a great idea. 

Would it have a predefined list of tasks to pick from to manage our expectations about when to use it versus using Slack?

What about notifying the requester? Could it ping an email when it’s moved to done so you don’t get swamped with “has it been done yet?” questions? 🙂

**Comment by alextercete** [comment]
Just an idea, but maybe we could have a private GitHub repository (to which all the organisers would have access) and then tickets could be GitHub issues? It would keep everything visible to all organisers, which might not be acceptable, but it would not require custom-building (and maintaining) something.

**Comment by brunogirin** [comment]
Great idea! It can start with a limited set of actions and see how it evolves.

**Comment by KimberleyCook** [comment]
@garrettc no defined list, it would be am empty input field for to tell us what you need, and then if we need to enquire more we can.

@alextercete Very true, we do already use Trello to manage tasks so I didn't want another list of things to do somewhere else.

**Comment by saljuama** [comment]
There is a github-trello integration already, not sure if that would fit the needs, could be worth checking out

**Comment by KimberleyCook** [comment]
I've created a Google form instead ➡️ https://forms.gle/uZXBziGC2f6GvHtw5.

Once the form has been submitted it will create a ticket in a Trello board for myself or @matyikriszta to do 🎉
