### ISSUE TITLE
Scaling the virtual workshop capability

### ISSUE THREAD

**Issue by brunogirin** [codebar/chapter-organiser-meetings#31]
We had a clash of dates between West London and Bristol today when scheduling a virtual workshop. We resolved it but looking through the planning spreadsheet, it looks like the available slots get filled in quickly and we are in danger of seeing the more active chapters crowd out the less active ones. To scale the capacity, we should be able to run virtual workshops for multiple chapters at the same time or to combine them into larger workshops.

Suggestion of how it could work with multiple chapters concurrently, e.g. Bristol and West London:
- 1 virtual-bristol channel + 1 virtual-west-london channel where greeting and pairing happens as it does today
- split the pairing rooms, e.g. pair-1 to pair-20 for Bristol, pair-21 to pair-40 for West London
- quick chat between organisers of both chapters after pairing to see if any chapter has extra students or coaches and if we can do extra pairs

**Note:** we can do several workshops in the same day if they are on different timezones with 3+ hours difference, e.g. any European chapter could do a workshop the same day as Savannah as they wouldn't overlap. So the problem is really for the European chapters.

**Comment by despo** [comment]
@brunogirin we are already doing a Scottish chapters workshop next Thursday at the same time as Norwich, and the plan is to follow the pattern that you mentioned above! There haven't been any discussions yet because the invitations for the Glasgow and Edi joined workshop will be going out tomorrow!

**Comment by KimberleyCook** [comment]
On Thursday 7th May Bristol and Norwich are both going to ruin in sync to see if it's possible. We have also updated the spreadsheet to allow for several events in one evening.

I am also going to send a feedback form to community members to see how we can improve them.
