### ISSUE TITLE
Opening codebar blog to all members

### ISSUE THREAD

**Issue by despo** [codebar/chapter-organiser-meetings#32]
Organisers to let attendees know that we would be happy to have them be guests on our blog in order for them to post different content. Maybe part of the workshop/virtual workshop introductions.
(Posts about something they've learne, their codebar experience, introducing different topics to students (coach posts) etc)

**Comment by KimberleyCook** [comment]
Discussed that we need to publicise the blog more, and ask organisers to share within their chapters if anyone would like to contribute?
