### ISSUE TITLE
Instagram Lives

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/chapter-organiser-meetings#33]
Last Monday I did an Instagram Live Q&A from the main codebar account, it went really well and I ended up spending an hour on there answering questions. I asked people whether I should do another one and people said yes. But this time I’d love to bring another chapter in. You would join from your chapter Instagram account to chat all things codebar, your chapter, or anything else you want to discuss. This will help promote your chapter and your chapter’s Insta account.

**Comment by matyikriszta** [comment]
Possible guests:
- coaches
- folks outside the community who are doing interesting things in/with tech
- chapter organisers
- organizations we want to boost
