### ISSUE TITLE
Mentorship: publishing tech articles and books

### ISSUE THREAD

**Issue by brunogirin** [codebar/chapter-organiser-meetings#35]
Technical web sites, journals and books are a major avenue to learn about technology. Unfortunately, the diversity problem in tech is just as severe in the publishing industry and very few authors come from under-represented groups. As someone with a book addiction, I have a ridiculous number of books from the Pragmatic Bookshelf so I asked them what we could do to raise the voices of Black and marginalised people in tech.

Pragmatic Bookshelf already work with Tech Ladies and Black Girls Code but admit that they have a dearth of diverse authors because they rely on unsolicited submissions coming in. However, [their submission process is open and covers short-format writing (articles) as well as other content](https://pragprog.com/become-an-author/) so could be a good place to start for whoever is interested in getting technical writing published.

So I suggested to them that maybe an organisation like codebar could help students in filing in publishing submissions, probably starting with short articles, so that they would get more diverse submissions. Their answer was: "great idea, let me get our executive editor and proposals admin up to speed and we'll be in touch shortly."

Assuming that the rest of their team agree it is a good idea, what can we do to mentor students through the submission process?

One way to get started could be in conjunction with codebar monthly: can some of the talks be turned into articles?

**Comment by KimberleyCook** [comment]
I'm wondering whether a workshop on technical writing would interest people?

**Comment by KimberleyCook** [comment]
We're partnering with Pragmatic Publishers for a Intro to Technical Writing event.
