### ISSUE TITLE
Attracting more coaches?

### ISSUE THREAD

**Issue by brunogirin** [codebar/chapter-organiser-meetings#4]
The flip side of issue #1 is that the West London chapter (and the central London one to some extent) has a lot of students but struggles to find coaches. In particular, we've seen a significant influx of new students and we now regularly have long student waiting lists. Pool ideas about:
- How do we reach out to existing coaches?
- How do we attract new coaches?
- How do we help existing students become coaches (a few in the group are interested)?

**Comment by KimberleyCook** [comment]
**Bruno** - Advertise to friends
**Jo** - Variation of hosts
**Kriszta** - Going to meetups and doing a 5 minute talk
**Kevin** - Find big employees with large dev teams
**Kim** - Mention to host to ask dev team if they want to get involved
**Kim** - community partnerships with conferences
**Bruno** - More people on codebar stories 

Action 
- more people on codebar stories
