### ISSUE TITLE
Mentoring companies on improving diversity in their teams

### ISSUE THREAD

**Issue by brunogirin** [codebar/chapter-organiser-meetings#41]
We had a great session during uncodebar on "Improving diversity in our teams" and it appears that:
- a fair few teams struggle to do that
- there is also a difficulty in hiring juniors

As a start I was wondering if we could start putting some shared resources together to help existing codebar coaches and sponsors improve the diversity of the teams they work in. We will probably end up with some actions that need to be taken at management levels and others that can be taken in the team itself.

**Comment by KimberleyCook** [comment]
HIRING JUNIOR DEVS IN YOUR TEAM

- Create a Slack channel to continue the discussion from the uncodebar session
- Take notes from said Slack channel and start putting together a document 
- Interview companies who have taken on junior devs/interns to ask what worked and didn't work
- Put together a document that can be shared amongst our community who can share with their companies


Create a doc later for `Improving diversity in our teams` but for now, we will focus on a doc for hiring juniors.
