### ISSUE TITLE
London student/coach imbalance impacts other chapters

### ISSUE THREAD

**Issue by brunogirin** [codebar/chapter-organiser-meetings#42]
The London and West London chapters have historically had a high number of students compared to the number of coaches, with long student waiting lists. For example, the West London main list typically fills up within 1 hour of the workshop being made live and the waiting list is often larger than the main list. This problem was limited to those two chapters when we had face to face workshops. However, now that we have virtual workshops, we see a signficant number of London students attend workshops with other chapters because they struggle to attend London workshops. This then poses a problem to those other chapters who see an influx of London students but no corresponding influx of coaches.

I have no idea how we can address that without penalising one group of students or another. Suggestions welcome.

**Comment by gnclmorais** [comment]
Could we remind coaches they can also help other chapters? Incentivise them, perhaps?

**Comment by KimberleyCook** [comment]
- Event dedicated to debugging coaching
- Coach training
- Tiered coaching on chapter pages??
- Social push for what being a coach involves?
- Discuss more of the technical benefits to being a coach.
- More info on the coach guide on the website
- Additional question on codebar stories about coaching
