### ISSUE TITLE
How can we make organising and running events less manual?

### ISSUE THREAD

**Issue by gnclmorais** [codebar/chapter-organiser-meetings#43]
I’m just coming from my first event as an organiser and I believe we can automate more things… So before suggesting anything, I would like to hear other people’s suggestions about this, any idea of the realms of _“if we could…”_!

**Comment by KimberleyCook** [comment]
- Optimise the checking in process
- Separate project for checking people in??
- Chase BCN about the pairing tool 
- Automated email to coaches with no skills who have RSVP'd
- Send emails from website on admin workshop page
- Inviting people to Slack - add email to CSV or Slackbot to invite
