### ISSUE TITLE
Translate the codebar website and guides

### ISSUE THREAD

**Issue by brunogirin** [codebar/chapter-organiser-meetings#49]
We've talked a lot about translating the codebar website, guides and tutorials, mainly as a result of queries from European chapters. Doing so would make it possible to expand further into non-English speaking countries. However, even those of use who speak multiple languages are not professional translators and don't have the capacity to translate and support those translations going forward.

If at some point the organisation has the money to do so, would it be possible to hire professional translators to do the work? For each language, the work would probably consist of an initial stint to translate the existing stuff followed by small ad-hoc queries when the original in English changes.

**Comment by KimberleyCook** [comment]
100% something we should find a freelancer to do. Will action in the summer.

Germain and Bruno to open up PR for French translations.
