### ISSUE TITLE
Passing on concerns raised by coach when student attends more than one chapter

### ISSUE THREAD

**Issue by hellenward** [codebar/chapter-organiser-meetings#53]
We had a student attend Brighton virtually recently. Their coach raised a concern after that they were bringing work from their day job to get help with. We addressed with the student, but realised they were down to attend quite a few other virtual workshops from other chapters. Thought this could be a good discussion point - how best to pass information on to other organisers from other chapters and what the best way is to do this generally rather than approaching individual chapters as we did on this occasion. I wasn't sure if the organisers channel was the best place or not as it seems to mostly be general announcements on there rather than about individuals.

**Comment by AFed29** [comment]
I may not be able to attend this evening, but I've had similar experiences with one or two people bringing work or coursework to sessions. I've noticed them going to many different workshops in different chapters, and avoiding the chapter where I brought up the issue with them.

**Comment by KimberleyCook** [comment]
Thanks both. We'll 100% discuss this topic this evening.

**Comment by KimberleyCook** [comment]
Organisers to make use of the "Notes" feature on codebar profile. 

- Add Github issue to planner repo to add Flag icon to profile if a note has been added to the persons profile within the last 5 workshops RSVP'd for.

**Comment by KimberleyCook** [comment]
Issue created on repo here ➡️ https://github.com/codebar/planner/issues/1490

**Comment by gnclmorais** [comment]
https://github.com/codebar/planner/issues/1490 is now done, @hellenward and @AFed29, so any notes you add will be visible for a while while workshop organisers are doing their part. 👍

**Comment by KimberleyCook** [comment]
Moving this to closed, due to the new procedure where students cannot RSVP for 2 workshops within a 48 hour period.
