### ISSUE TITLE
Invitation timings - for discussion

### ISSUE THREAD

**Issue by hellenward** [codebar/chapter-organiser-meetings#54]
Brighton recently had feedback from a student that they nearly always miss our email invitations until later in the day and end up not getting a spot on the workshop. We would be interested to know if other chapters have had this feedback or whether they intentionally change the times to send the invite so people with different schedules can pick up.

**Comment by KimberleyCook** [comment]
We discussed a few options:

1) Differ the time and day the email invites are sent
2) Hold back a few spots for people who you know will 100% show up.
