### ISSUE TITLE
Pairing tool prototype 

### ISSUE THREAD

**Issue by saljuama** [codebar/chapter-organiser-meetings#56]
When running codebar workshops, as organisers we were struggling a little bit to organise the pairings between coaches and students, hence we did a web app to help ourselves with this task, and we have been trying it out for some virtual workshops now, and we think so far it has been helpful, this is why we want to share it with all the other chapters. 

Currently the [Pairing Tool](https://saljuama.github.io/codebar-pairing-tool/) is just a prototype, with some limitations, and some features being still not 100% polished, but after seeing that is valuable, we want to move forward, making it a bit more stable and usable and possibly add more features, so here feedback from other chapters could be useful, the sooner the better, so we could take not only our chapter needs into consideration 😄

**Comment by KimberleyCook** [comment]
Actions:

- Kim to give Salvador admin access to the current pairing-tool repo so he can override it with this project. 
- Once in a slightly more stable state he will share with organisers and get feedback
- Salvador will create a Project in this repo for feedback

**Comment by biggianteye** [comment]
Have there been any updates to this? The prototype as it stands is pretty useful and it would be good to formalise it so we can start getting support, adding improvements, etc.
