### ISSUE TITLE
Advanced Student Topics

### ISSUE THREAD

**Issue by KimberleyCook** [codebar/chapter-organiser-meetings#58]
There was a discussion on Wednesday about students who turn up with really advanced or niche topics and there are no coaches to help them.

**Comment by KimberleyCook** [comment]
Few points:
- Check the student list prior to the workshop, and drop them an email if you need clarification.
- If this is the case, explain to the student they should have a backup in case we don't have a coach. We do mention this in our student guide.
- If you want you can send a tweet/slack message asking for a coach to help with these skills. I feel this a good thing to do, to go that extra mile, but it's completely up to you.

**Comment by gnclmorais** [comment]
I just realised that our mentoring program could complement this…! 💡
