### ISSUE TITLE
PR collateral and assets

### ISSUE THREAD

**Issue by brunogirin** [codebar/chapter-organiser-meetings#6]
It would be useful for chapters to be able to print collateral such as leaflets and business cards. While doing that, there should be rules on how to use the logo and create such collateral so that we keep consistency between chapters both in terms of visuals and message.

Points I'd like to address:
- What collateral do we need? (initial suggestion: chapter business cards, recruitment leaflets, stickers)
- How do we produce that collateral? (option: I have a script that produces PDF suitable for Vistaprint or Moo that I'm happy to contribute)

**Comment by KimberleyCook** [comment]
1) Add all current assets people are using to the assets repo, so other chapters can have access to them

**TASK**
Bruno to add the script to the readme so chapters can generate all their own assets

**Comment by KimberleyCook** [comment]
Assets repo here -> https://github.com/codebar/assets
