### ISSUE TITLE
Serious lack of coaches

### ISSUE THREAD

**Issue by gnclmorais** [codebar/chapter-organiser-meetings#64]
I’m not sure if the other chapters feel the same, but for the past few workshops, the Central London chapter has struggled to get even five coaches. Are we doing something wrong? Can we do something better? Which promotional channels do we have to share our message and incentivise people to coach?

**Comment by KimberleyCook** [comment]
I've been chatting with companies about talking internally to their developer team about codebar, and how they can get involved. Hopefully this will get us more coach, I'll keep this note updated of where I do it and when.

Companies
- Simply Business 1/12/21
- Sabio 24/2/22
- IBDS ???

**Comment by KimberleyCook** [comment]
Create more video content aimed at coaches.

**LIVE**
- "Hear from our wonderful coaches" https://www.youtube.com/watch?v=YXDro52s-jU 

IDEAS 
- "A day in the life of" type videos- Inspiration https://www.youtube.com/watch?v=5yOyToRskfE

**Comment by KimberleyCook** [comment]
So far we have had 161 "non community member" RSVPs for codebar Festival. These are people who have never attended a codebar workshop before. My goal after the event is to encourage them to sign up to codebar as either a coach or student. 

As part of this at the end of the month (Monday 28th), I am going to run a virtual Open Day -> https://codebar.io/events/virtual-open-day-3. We've run 2 before and they were really helpful so hopefully, this will coincide nicely with the email to Festival participants.

**Comment by KimberleyCook** [comment]
Conference partnerships -

- Halfstack | London | September 2022
- London Web Standards | London |. September 2022
