### ISSUE TITLE
Onboarding coaches

### ISSUE THREAD

**Issue by khamiltonuk** [codebar/chapter-organiser-meetings#7]
- Converting students to coaches 
- How to handle expectation of what coaches should get out of the experience.
- Have coaches read the coaching guidelines?
- Have coaches read the code of conduct

**Comment by KimberleyCook** [comment]
1) Always try to have 2 organisers if possible so one can be signing in, and one can do any intros.
2) Ask an experience coach to help onboard any new coaches 
3) Put little stickers on regular attendees name badges so that new attendees can visually see someone who they can go and talk to
