### ISSUE TITLE
Should we archive the virtual-* channels?

### ISSUE THREAD

**Issue by brunogirin** [codebar/chapter-organiser-meetings#71]
Now that we have an official virtual codebar chapter (thanks Gonçalo!), should we archive the `virtual-*` channels?

**Comment by KimberleyCook** [comment]
Kim to catch with Gonçalo about the virtual chapter and then clean up Slack and Discord `virtual` channels.

**Comment by KimberleyCook** [comment]
Kim has cleaned this up
