### ISSUE TITLE
Finding companies to host

### ISSUE THREAD

**Issue by MMasey** [codebar/chapter-organiser-meetings#8]
One thing i struggle with is finding companies to host, other than the one I work for. Where I am I don't have a lot of large digital based companies and I've got in contact with probably over 30 different agencies and I've only ever heard back from a handful, and only one of them have offered to host.

It would be great to hear what everyone else does to find different companies to host their workshops.

**Comment by KimberleyCook** [comment]
Great topic to discuss!

**Comment by kplawver** [comment]
I try to avoid companies and work with non-profits or economic development groups.  They're more likely to have space that's not used in the evenings and thrilled to have someone using the space, and they _love_ being able to take credit for the programming.

**Comment by KimberleyCook** [comment]
- Trying to speak at meetups is a great way of advertising codebar
- Targeted facebook ads
- Small budget for help grow chapters

**Comment by MMasey** [comment]
Thanks for all the advice and help =D

**Comment by KimberleyCook** [comment]
We discussed this so I'm going to close the issue. If you do have any other ideas please do add them to this issue.
