### ISSUE TITLE
Staff turnover at host companies

### ISSUE THREAD

**Issue by brunogirin** [codebar/chapter-organiser-meetings#9]
As with every job, the contacts we have at host companies might one day leave the company and go somewhere else, at which point a host may unexpectedly become inactive. In the West London chapter, we try to have backup names to ensure continuity. However the web site only allows one contact so we have to store this separately.

Any idea to reduce host turnover would be great, in particular:
- Any ideas beyond having multiple contacts?
- Should the web site be updated to allow storage of multiple contacts?

Related issue: #8

**Comment by KimberleyCook** [comment]
- Update the website to allow for 2 host contacts

**Comment by KimberleyCook** [comment]
A PR is in by Despo adding the capability for more than 1 host.
